export const demoUser = {
  firstName: 'Alex',
  middleName: 'Santos',
  lastName: 'Rodriguez',
  email: 'alex@example.com',
};

export const credentials = [
  {
    id: 'google',
    name: 'Google',
    username: 'alex@gmail.com',
    website: 'accounts.google.com',
    category: 'Personal',
    initials: 'G',
    tone: '#E9F2EE',
    color: '#39775A',
    favorite: true,
    updated: 'Updated 3 days ago',
  },
  {
    id: 'github',
    name: 'GitHub',
    username: 'ac-rodriguez',
    website: 'github.com',
    category: 'Work',
    initials: 'GH',
    tone: '#ECEEED',
    color: '#28312E',
    favorite: true,
    updated: 'Updated yesterday',
  },
  {
    id: 'netflix',
    name: 'Netflix',
    username: 'alex@gmail.com',
    website: 'netflix.com',
    category: 'Entertainment',
    initials: 'N',
    tone: '#F8EAEA',
    color: '#A84343',
    favorite: false,
    updated: 'Updated 2 months ago',
  },
  {
    id: 'facebook',
    name: 'Facebook',
    username: 'alex.rodriguez',
    website: 'facebook.com',
    category: 'Social',
    initials: 'F',
    tone: '#EAF0F7',
    color: '#456A92',
    favorite: false,
    updated: 'Updated 6 months ago',
  },
  {
    id: 'spotify',
    name: 'Spotify',
    username: 'alex@gmail.com',
    website: 'spotify.com',
    category: 'Entertainment',
    initials: 'S',
    tone: '#E8F4EB',
    color: '#367747',
    favorite: false,
    updated: 'Updated 8 months ago',
  },
  {
    id: 'microsoft',
    name: 'Microsoft',
    username: 'alex@outlook.com',
    website: 'account.microsoft.com',
    category: 'Work',
    initials: 'M',
    tone: '#F7EFE4',
    color: '#9A651C',
    favorite: false,
    updated: 'Updated 4 days ago',
  },
  {
    id: 'cvsu',
    name: 'Cavite State University',
    username: 'student@example.edu',
    website: 'cvsu.edu.ph',
    category: 'School',
    initials: 'CV',
    tone: '#EEF0E6',
    color: '#68723D',
    favorite: false,
    updated: 'Updated 5 days ago',
  },
  {
    id: 'discord',
    name: 'Discord',
    username: 'acdev',
    website: 'discord.com',
    category: 'Social',
    initials: 'D',
    tone: '#EFEDF7',
    color: '#655B91',
    favorite: false,
    updated: 'Updated 3 weeks ago',
  },
];

export const categories = [
  { name: 'All', count: 24 },
  { name: 'Social', count: 5 },
  { name: 'Work', count: 6 },
  { name: 'Finance', count: 3 },
  { name: 'Entertainment', count: 4 },
  { name: 'School', count: 2 },
  { name: 'Personal', count: 4 },
];

export const securityFindings = [
  {
    title: 'Weak passwords',
    detail: '2 accounts',
    description: 'Replace short or predictable passwords.',
    severity: 'warning',
  },
  {
    title: 'Reused passwords',
    detail: '1 password reused',
    description: 'The same password appears on three accounts.',
    severity: 'danger',
  },
  {
    title: 'Compromised passwords',
    detail: '0 detected',
    description: 'No known exposure was found.',
    severity: 'safe',
  },
  {
    title: 'Old passwords',
    detail: '4 accounts',
    description: 'Unchanged for more than one year.',
    severity: 'neutral',
  },
];
